version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: imcjk-fastapi-backend
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - ./Backend/.env
    depends_on:
      - mysql
      - redis
    networks:
      - imcjk-net

  mysql:
    image: mysql:8.0
    container_name: imcjk-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feitwnd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - imcjk-net

  redis:
    image: redis:7.2-alpine
    container_name: imcjk-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - imcjk-net

networks:
  imcjk-net:
    driver: bridge

volumes:
  mysql-data:
